version: '3.7'

services:
  influxdb:
    image: influxdb:1.7-alpine
    volumes:
      - influxdb:/var/lib/influxdb

  telegraf:
    build: ./telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf

  grafana:
    image: grafana/grafana:6.7.1
    ports:
      - '3000:3000'

volumes:
  influxdb:
  grafana:

